### ISSUE TITLE
Candidates of errors to remove from PMD/spotbugs checks

### ISSUE THREAD

**Issue by BenWhitehead** [GoogleCloudPlatform/java-repo-tools#171]
Coming from the standpoint of Firestore samples projects

* `IMC_IMMATURE_CLASS_NO_TOSTRING` we usually don't have toString for many classes intentionally
* `SIC_INNER_SHOULD_BE_STATIC_ANON` for query watch where a callback has to be supplied (sure it could be a separate class from a type signature standpoint, but that moves the code away from the sample)
* `PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS` the code in question is creating the initial dataset to show how queries work, and necessarily have to call the same methods a few times

**Comment by lesv** [comment]
Will be in next release
