### ISSUE TITLE
Import com.google.cloud:libraries-bom in <dependencyManagement>

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/java-repo-tools#284]
[Libraries BOM](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM) is the recommended way of managing versions for GCP client libraries.

I've ran into a problem with split versions between `gax` and `gax-grpc` when working on GoogleCloudPlatform/java-docs-samples#5836. I am fine with applying a workaround (either forcing a `gax` version, or importing the BOM on the individual sample level), but it may make sense to do it for all samples.

The counterargument is that all samples should function well without the `shared-configuration` parent, so setting versions on the parent is not desirable.

**Comment by suztomo** [comment]
Memo:
Many of the samples in Java-docs-samples repository use the Libraries BOM
 https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5808/files

**Comment by elefeint** [comment]
That's probably the way for me to go then. Closing this issue.
