### ISSUE TITLE
git submodule?

### ISSUE THREAD

**Issue by jendap** [GoogleCloudPlatform/java-repo-tools#40]
Why "This repository is copied into a subtree of other Java repositories"? That and all the subsequent explanation is just unfortunate.

What is wrong with git sub-modules? It would have made stuff a lot more natural. Plus many projects (even google projects) are using them. Why not this?

**Comment by tswast** [comment]
I originally did use submodules: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/115

The reason for not using submodules is that we have many samples and tutorials that would need to get updated to use the recursive clone, which is a lot of documentation to update.

Anyway, it shouldn't be necessary anymore. I published the pom which can be used as a parent to Maven central yesterday. http://search.maven.org/#search%7Cga%7C1%7Ccom.google.cloud.samples I need to update our samples to use that and then remove the sub-tree instructions from this repos readme.

**Comment by jendap** [comment]
I have not really studied what you use this repo for...

Of course the common parent pom is good. However that pom should probably not have local path to checkstyle. Better might be to build it into a jar file and add it as dependency. Or you can inline it inside the pom itself (but that is worse choice). Also the hardcoded tagBase in maven-release-plugin is probably not what you want. Perhaps variable which would be overwritten by projecs inheriting from it is better.

And then you may still want to have something like CONTRIBUTING.md or ISSUE_TEMPLATE.md as a submodule in ".github". In which case you may put there a few more things like that checkstyle config and forget the jar file thing.

Anyway, do as you want. I was just surprised to see it copied in multiple repositories.

**Comment by tswast** [comment]
Thanks for the tips! Yeah, it's my goal to make it so I don't have to copy this everywhere.

**Comment by jendap** [comment]
cool, thanks
