### ISSUE TITLE
Safe to remove this when using a sample project?

### ISSUE THREAD

**Issue by Orbyt** [GoogleCloudPlatform/java-repo-tools#60]
I used one of the GAE quickstarts to quickly get some boilerplate files for my project. I noticed that builds were failing due to a `checkstyle` plugin, and after investigation ended up here.

It looks like the `checkstyle` plugin is added in if the following code from the quickstart is left in:

```
<parent>
    <groupId>com.google.cloud.samples</groupId>
    <artifactId>shared-configuration</artifactId>
    <version>1.0.1</version>
   </parent>
```

Is it safe to remove this? I understand removing it will get rid of the `checkstyle` plugin, which is desired, however I am unsure what other dependencies might be removed, and don't want to remove something that is critical.

**Comment by tswast** [comment]
This package should not include any shared dependencies, only plugins for testing/version updates/checkstyle. It should be safe to remove from any sample you see on Google Cloud Platform.

If a sample does not work after removing the parent, please file an issue on the repo where the sample is hosted.

P.S. I'd very much like to add the parent in our samples only at test time to make this clearer, but I haven't gotten around to it, yet.

**Comment by Orbyt** [comment]
@tswast Thank you, i'll go ahead and close this then.
