### ISSUE TITLE
Checkstyle's custom google import order is now out of date

### ISSUE THREAD

**Issue by cgruber** [GoogleCloudPlatform/java-repo-tools#69]
Google moved to a simpler import order, and now this checkstyle does not reflect that order, which is:

static imports lexically ordered
<space>
imports lexically ordered

**Comment by tswast** [comment]
CC @lesv @jabubake 

FYI: We're tracking this internally at bug number 29834352.

**Comment by lesv** [comment]
Fixed in #75
